### ISSUE TITLE
(For MacOS-users): Problems running the notebook

### ISSUE THREAD

**Issue by AntonSteino** [ChampionApe/EnergyEconomicsE2023#4]
I think I might have solved the problem with running the notebook, some MacOS-users encountered. There are several 'stdPackages.ipynb' files around in the directory, and for MacOs-users, the path conventions cause some problems. The trick is to use '/' instead of '\\'. An easy way to solve it is to change one line of code in the 'stdPackages.ipynb'-file located here:

../EnergyEconomicsE2023/Exercises

If you change line 4 in the first cell, the whole thing seems to work:

from: os.chdir(os.getcwd().split('\\Exercises')[0]) #WindowsOS
to: os.chdir(os.getcwd().split('/Exercises')[0]) #MacOS

**Comment by jonas-hass-bonne** [comment]
The issue should be fixed with the latest update to the repository
